### ISSUE TITLE
Getting an error when trying to open tableplus

### ISSUE THREAD

**Issue by mikemuller** [tanc/lando-db-tools#3]
Thank you for this plugin. I've been looking for one for a while! I installed and am getting this error:
ERROR ==> undefined is not a function
Any idea?

**Comment by mikemuller** [comment]
Just wondred if any progress has been made on this? Thanks!

**Comment by dalin-** [comment]
The open PR fixes the issue.  It's not just an issue with tableplus, but with the plugin as a whole in modern versions of Lando.

**Comment by tanc** [comment]
Thanks! I don't use Lando anymore so can't check whether things work but I'm happy to merge the PR if that helps
